### ISSUE TITLE
npm run dev 有报错，http://127.0.0.1:8000/无法访问

### ISSUE THREAD

**Issue by dxxfire** [ant-design/antd-bin#11]
报错信息如下：

> antd-demo@1.0.0 dev G:\coding\antdone
> antd server

listened on 8000
error ./src/component/App.jsx
Module not found: Error: Cannot resolve module 'antd/lib/datepicker' in G:\codin
g\antdone\src\component
resolve module antd/lib/datepicker in G:\coding\antdone\src\component
  looking for modules in C:\Users\BYONE\AppData\Roaming\npm\node_modules\antd-bi
n\node_modules
    C:\Users\BYONE\AppData\Roaming\npm\node_modules\antd-bin\node_modules\antd d
oesn't exist (module as directory)
[C:\Users\BYONE\AppData\Roaming\npm\node_modules\antd-bin\node_modules\antd]
 @ ./src/component/App.jsx 13:25-55
error ./src/common/lib.js
Module not found: Error: Cannot resolve module 'antd/lib/index.css' in G:\coding
\antdone\src\common
resolve module antd/lib/index.css in G:\coding\antdone\src\common
  looking for modules in C:\Users\BYONE\AppData\Roaming\npm\node_modules\antd-bi
n\node_modules
    C:\Users\BYONE\AppData\Roaming\npm\node_modules\antd-bin\node_modules\antd d
oesn't exist (module as directory)
[C:\Users\BYONE\AppData\Roaming\npm\node_modules\antd-bin\node_modules\antd]
 @ ./src/common/lib.js 3:0-29

Hash: 4e427d07a13e99f0ecd8
Version: webpack 1.9.13
Time: 1379ms
       Asset     Size  Chunks             Chunk Names
    index.js  3.12 kB       0  [emitted]  index
index.js.map  2.66 kB       0  [emitted]  index
chunk    {0} index.js, index.js.map (index) 1.09 kB [rendered]
    [0] ./src/entry/index.jsx 361 bytes {0} [built]
    [1] ./src/common/lib.js 45 bytes {0} [built] [1 error]
    [2] ./src/component/App.jsx 638 bytes {0} [built] [1 error]
    [3] external "window.React" 42 bytes {0} [not cacheable]

ERROR in ./src/component/App.jsx
Module not found: Error: Cannot resolve module 'antd/lib/datepicker' in G:\codin
g\antdone\src\component
 @ ./src/component/App.jsx 13:25-55

ERROR in ./src/common/lib.js
Module not found: Error: Cannot resolve module 'antd/lib/index.css' in G:\coding
\antdone\src\common
 @ ./src/common/lib.js 3:0-29
webpack: bundle is now VALID.

请问是什么问题？很看好该项目，但是一开场就不顺，很郁闷啊。烦请帮助解决，万分感谢！

**Comment by sorrycc** [comment]
先 npm install 下。

**Comment by dxxfire** [comment]
安裝了bluebird的情況下，为什么还提示要安装bluebird???
$ npm install bluebird
npm WARN package.json antd-demo@1.0.0 No repository field.
npm WARN package.json antd-demo@1.0.0 No license field.
bluebird@2.9.34 node_modules/bluebird
$ sudo npm run dev

> antd-demo@1.0.0 dev /home/admin/tmp
> antd server

The file "/usr/lib/node_modules/antd-bin/node_modules/koa/node_modules/composition/index.js" requires `Promise`,
but neither `bluebird` nor the native `Promise` implementation were found.
Please install `bluebird` yourself.

**Comment by yiminghe** [comment]
node 升级为 0.12 版本

**Comment by dxxfire** [comment]
# 1. 最开始在npm i antd-bin -g的时候有报错，

npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "antd-bin" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path ../lib/node_modules/antd-bin/bin/antd
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, symlink '../lib/node_modules/antd-bin/bin/antd'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, symlink '../lib/node_modules/antd-bin/bin/antd']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../lib/node_modules/antd-bin/bin/antd' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

### 于是使用sudo npm i antd-bin -g，结果导致了后面一系列稀奇古怪的问题。所以需要先解决该问题。

## 参考  https://docs.npmjs.com/getting-started/fixing-npm-permissions（http://www.ruanyifeng.com/blog/2015/05/command-line-with-node.html的留言中看到该解决方案）：

```
Change the owner of npm's directory's to the effective name of the current user (your username!):

 sudo chown -R `whoami` <directory>
```

If you don't want to change the permissions on the entire directory, you can change permissions on the subfolders lib/node_modules, bin, and share.

## 将这3个目录的权限赋予当前用户后安装成功。

# 2. 之后npm install

npm WARN package.json antd-demo@1.0.0 No repository field.
npm WARN package.json antd-demo@1.0.0 No license field.
npm WARN prefer global jshint@2.8.0 should be installed with -g

## 按照提示安装 npm install jshint -g

# 3. npm run dev提示有错误：

ERROR in ./~/antd/~/rc-calendar/~/rc-align/lib/Align.js
Module not found: Error: Cannot resolve module 'dom-align' in /home/admin/nodejs/code/test/one/node_modules/antd/node_modules/rc-calendar/node_modules/rc-align/lib
 @ ./~/antd/~/rc-calendar/~/rc-align/lib/Align.js 21:16-36
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 514 kB [rendered]
        [0] ./~/antd-bin/~/css-loader?sourceMap&-restructuring!./~/antd-bin/~/autoprefixer-loader!./~/antd/lib/index.css 512 kB {0} [built]
        [1] ./~/antd-bin/~/css-loader/lib/css-base.js 1.51 kB {0} [built]
webpack: bundle is now VALID.
^C

## 安装npm install dom-align

# 4. npm run dev正常启动了。

# 版本号

$ node -v
v0.12.7
$ npm -v
2.11.3
