### ISSUE TITLE
好像没有配置react hot loader吧，自己该怎么配置呢？

### ISSUE THREAD

**Issue by xiongxin** [ant-design/antd-bin#14]
好像没有配置react hot loader吧，自己该怎么配置呢？

**Comment by afc163** [comment]
`--hot`

**Comment by xiongxin** [comment]
是`npm run dev --hot`吗？
还有一个问题就是我现在使用antd-bin 0.6.1，antd init生成的文件,package.json中antd-bin的版本还是`"antd-bin": "0.5.x"`，应该要更新一下了吧
