### ISSUE TITLE
提供单独的 antd-build

### ISSUE THREAD

**Issue by yiminghe** [ant-design/antd-bin#16]
去除 server， hot load 等功能

/Users/sean/code/javascript/emcoo/node_modules/antd-bin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client dependency git url: https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz

, maybe very slow, please keep patience...

**Comment by xujihui1985** [comment]
+1

**Comment by sorrycc** [comment]
https://github.com/ant-design/antd-build
