### ISSUE TITLE
使用 yeoman 或其他 scaffold 工具代替 antd init

### ISSUE THREAD

**Issue by afc163** [ant-design/antd-bin#19]
目前的痛点是需要首先安装 antd-bin 到全局用于 init 。

然后还要在项目目录里安装一遍 `antd-bin`，用于 scripts 的命令。

```
$ npm install antd-bin -g
$ mkdir antd-demo && cd antd-demo
$ antd init
$ npm install  // 这里又会安装一遍 antd-bin
```

解决方案有两种：
1. 使用 yeoman 或 [slush](http://slushjs.github.io/)
   
   ``` bash
   $ npm install yeoman -g
   $ npm install generator-antd -g
   $ mkdir antd-demo && cd antd-demo
   $ yo antd
   ```
2. 或者抽离 antd-init
   
   ``` bash
   $ npm install antd-init -g
   $ mkdir antd-demo && cd antd-demo
   $ antd init
   $ npm install
   ```

**Comment by afc163** [comment]
方案二确实简单点。

**Comment by afc163** [comment]
`tnpm install` 或 `npm install` 做到 `antd init` 里去简化步骤。

**Comment by sorrycc** [comment]
install 怎么整合? tnpm 直接放进去不合适。那么内置 npm install，然后提供 registry 配置，但是 tnpm 的源地址很难记啊。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/develop-0.10.0/scripts/install.js

这个方法不错。

**Comment by sorrycc** [comment]
好了。
- antd-init@0.1.1
- antd-bin@0.9.0

**Comment by afc163** [comment]
效率略高。:+1:
