### ISSUE TITLE
将来antd-bin是否支持浏览器自动刷新？

### ISSUE THREAD

**Issue by Tinker404** [ant-design/antd-bin#25]
如何进行配置，可以写个实例参考一下吗

**Comment by sorrycc** [comment]
- livereload 只是刷新页面，感觉意义不大
- 尝试过 [react-hot-loader](https://github.com/gaearon/react-hot-loader)，有不少坑，过段时间再试试

**Comment by Tinker404** [comment]
@sorrycc 感激不尽，github上看了很多例子，都写得比较复杂，想配置到antd-bin上一直报错。

现在双屏如果有livereload的话效率会高很多，每次切过去点到浏览器再刷新很繁琐。
