### ISSUE TITLE
npm run build not wrok on windows system

### ISSUE THREAD

**Issue by 0xryanz** [ant-design/antd-bin#28]
【rm -rf dist && antd-build && mkdir -p dist/${npm_package_name}/${npm_package_version} && mv dist/_._ dist/${npm_package_name}/${npm_package_version}/】
The script can only be implemented under Linux， Recommended adding the description， To avoid misunderstanding

**Comment by sorrycc** [comment]
这个可以根据自己的需要写，并没有封装在工具里面。
