### ISSUE TITLE
关于默认配置项

### ISSUE THREAD

**Issue by yozman** [ant-design/antd-bin#3]
`antd server` 运行之后，
打开地址 `localhost:8000`，
默认访问的是当前目录下的 `index.html`。
怎么配置添加识别其他文件？
例如 `index.htm`

BTW 刚看到 [ant.design](http://ant.design) 好像快要完成了呢～，
设计标签也激活了，加油～
出正式版，我直接上 ^__^

**Comment by sorrycc** [comment]
用 index.html 吧，依赖的 koa-static 不支持配置多个 index 。
