### ISSUE TITLE
The package atool-build@0.4.2 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by xzedx** [ant-design/antd-bin#32]
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/jj/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/jj/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package atool-build@0.4.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer dora-plugin-hmr@0.1.3 wants atool-build@^0.3.1
npm ERR! peerinvalid Peer dora-plugin-atool-build@0.2.1 wants atool-build@^0.4.2

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jj/Workplace/Frontend/antd/playground/npm-debug.log

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/issues/5
